### ISSUE TITLE
New info about res.json()

### ISSUE THREAD

**Issue by anselb** [lowewenzel/nested-apis#2]
At first, I was confused as to why the genres route responded with an array, as I had thought that res.json() could only return an object. After looking though the official website of JSON on json.org, I found out that there are a lot of data types that are considered to be JSON, and an array is one of them.

Also, your server says it's listening on 3000, but it looks like it's listening on 3001.

**Comment by lowewenzel** [comment]
Changed console log `3000` to `3001`. Ref commit #cef34df. Thank you!
